### ISSUE TITLE
several issues preventing for running

### ISSUE THREAD

**Issue by Phil353556** [HalilDeniz/DNSWatch#2]
Hi,
I tried but no success

1/ I run the git command
2/ I run the pip command (pip install -r requirements.txt)
hum a cd command to DNSWatch subdirectory is mandatory before 2/
t
hen
severals caracters found in comments prevent from running 
examples:
```
 File "dnswatch.py", line 19
SyntaxError: Non-ASCII character '\xc4' in file dnswatch.py on line 19, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
I delete theses words/caracters

then syntax errors:only comments are hitted,
one example, but there are many
```
 File "dnswatch.py", line 31
    print(f"{Fore.RED}[!] Error resolving DNS over HTTPS: {e}{Style.RESET_ALL}")
                                                                              ^
SyntaxError: invalid syntax
```
may be it  is  printf(   and not only print(  as I dont' know I just deleted the f caracter 

same for write command
```
 File "dnswatch.py", line 78
    file.write(f"DNS Request  from {dns_src_ip} to {dns_dest_ip} at {timestamp}: {dns_request} (Type: {dns_type})\n")
                                                                                                                   ^
SyntaxError: invalid syntax
```
f has been deleted 

at the end:
the pip was succeded and the directory added to PATH 
```
$ pip install -r requirements.txt 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting scapy (from -r requirements.txt (line 1))
  Downloading https://www.piwheels.org/simple/scapy/scapy-2.5.0-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.5MB 250kB/s 
Requirement already satisfied: argparse in /usr/lib/python2.7 (from -r requirements.txt (line 2)) (1.2.1)
Installing collected packages: scapy
  The script scapy is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed scapy-2.5.0
```
echo $PATH is Ok following a export PATH=$PATH:/home/pi/.local/bin  
scapy is there:
```
$ pip list | grep scapy
scapy             2.5.0
```      

however it doesn't work
```
$ sudo python dnswatch.py -i eth0 -k 192.168.6.191 -o dns_results.txt
Traceback (most recent call last):
  File "dnswatch.py", line 6, in <module>
    from scapy.all import *
ImportError: No module named scapy.all
```

many thanks for your help

**Comment by HalilDeniz** [comment]
I have tried many times before I shared the tool. but I did not encounter error issues. but we can solve this together as soon as possible

**Comment by Phil353556** [comment]
Hi
Thank you so much for your help

Try to run on a raspberry pi 4

Envoyé avec la messagerie sécurisée [Proton Mail.](https://proton.me/)

------- Original Message -------

**Comment by Phil353556** [comment]
Hi,
Good catch for python, by default .. the link is python to python2
however python3 is linked to python3.7
and the result is the same:
```
$ sudo python3.7 dnswatch.py -i eth0 -k 192.168.6.191 -o dns_results.txt
Traceback (most recent call last):
  File "dnswatch.py", line 6, in <module>
    from scapy.all import *
ModuleNotFoundError: No module named 'scapy'

```
How to solve this issue ?

**Comment by Phil353556** [comment]
Hi again,
I go deeper.

```
$ pip install -r requirements.txt 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: scapy in /home/pi/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (2.5.0)
Requirement already satisfied: argparse in /usr/lib/python2.7 (from -r requirements.txt (line 2)) (1.2.1)

```
Ah this is because there is a link python to python2 so it is modified:

```
# cd /usr/bin/
# ls -larlt python
lrwxrwxrwx 1 root root 7 Mar  4  2019 python -> python2

# rm python
 ln -s python3 python
# ls -larlt python
lrwxrwxrwx 1 root root 7 Aug 30 12:31 python -> python3
```
then pip again, twice to check where it is installed:

```
$ pip install -r requirements.txt 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting scapy (from -r requirements.txt (line 1))
  Using cached https://www.piwheels.org/simple/scapy/scapy-2.5.0-py2.py3-none-any.whl
Collecting argparse (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Installing collected packages: scapy, argparse
Successfully installed argparse-1.4.0 scapy-2.5.0

$ pip install -r requirements.txt 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: scapy in /home/pi/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.5.0)
Requirement already satisfied: argparse in /home/pi/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.4.0)
```

However sames results :-1: 
```

 $ sudo python  dnswatch.py -i eth0 -k 192.168.6.191 -o dns_results.txt
Traceback (most recent call last):
  File "dnswatch.py", line 6, in <module>
    from scapy.all import *
ModuleNotFoundError: No module named 'scapy'

 $ sudo python3  dnswatch.py -i eth0 -k 192.168.6.191 -o dns_results.txt
Traceback (most recent call last):
  File "dnswatch.py", line 6, in <module>
    from scapy.all import *
ModuleNotFoundError: No module named 'scapy'
```
Thank you for your help

**Comment by HalilDeniz** [comment]
god, i have no idea about this.
Can you do 
apt-get install python3-scapy?

**Comment by Phil353556** [comment]
some good some bad

**good:**`    $ sudo apt-get install python3-scapy`
             yes not it runs!
             does that mean  pip command is not required?
             it works better 
             
```
$ sudo python3  dnswatch.py -i wlan0  -o dns_results.txt
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(dnswatch.py:5959): Gdk-CRITICAL **: 12:52:12.774: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(dnswatch.py:5959): Gdk-CRITICAL **: 12:52:12.777: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
[+] DNS Request  from 192.168.6.18 to 192.168.6.19 at 2023-08-30 12:52:19: optimizationguide-pa.googleapis.com. (Type: 28)
```


I connect using ssh -X  but nothing better on messages "unable to init server" and "Gdk-CRITICAL" .  any idea?

**bad:** 
        `dnswatch.py: error: unrecognized arguments: -k 192.168.6.191`
        option -k is written in the example paragraph, however it is not displayed using the --help option ?

**Comment by Phil353556** [comment]
That's great, Thank you.
-If the command   apt-get install python3-scapy  is used,  does the pip command also needed ?

- I solved "unable to init server" and "Gdk-CRITICAL" messages with a correct SSH X11Forwarding configuration :-) 
  The file /etc/ssh/sshd_config must contains:
    X11Forwarding yes
   X11DisplayOffset 10
   X11UseLocalhost no
    However I don't understant X11 is needed by DNSWatch?

**Comment by Phil353556** [comment]
dnswatch runs for a few hours, then Ctrl-C,  
Question: why this IP adress is written so many times?
FYI: 192.168.6.19 is the raspberry where dnswatch runs, but also, most important, where ADGuard runs, and act as a DNS for all the internal network.
```
Most Resolved by: 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19, 192.168.6.19

DNS Type Analysis:
Type: 1 - Count: 8275
Type: 28 - Count: 6190
Type: 6 - Count: 1199
Type: 5 - Count: 2478
Type: 65 - Count: 1132
Type: 12 - Count: 114
Type: 33 - Count: 8

```
Thank you.

**Comment by HalilDeniz** [comment]
I will fix this problem as soon as possible, if you have programming knowledge, feel free to pull request.
